/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_roboracers_gaeldrive_tests_cppTest */

#ifndef _Included_com_roboracers_gaeldrive_tests_cppTest
#define _Included_com_roboracers_gaeldrive_tests_cppTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roboracers_gaeldrive_tests_cppTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_roboracers_gaeldrive_tests_cppTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
